galaxy_info:
    author: iamabhishek-dubey
    description: Install and configure Prometheus Exporters
    license: GPLv3

    min_ansible_version: 2.3

    platforms:
        - name: Ubuntu
          versions:
              - xenial
              - precise
              - trusty
        - name: Debian
          versions:
              - jessie
              - wheezy
        - name: EL
          versions:
              - 6
              - 7
    galaxy_tags:
        - system
        - monitoring
        - prometheus

dependencies: []
