---
# vars file for osm_prometheus_exporter
db_root_password: "password"

#### Variables for Node Exporter ####
node_exporter_version: "0.17.0"

#### Variables for Solr Exporter ####
solr_exporter_version: "0.3.9"
solr_ip: "localhost"
solr_port: "8983"

#### Variables for Apache Exporter ####
apache_exporter: "0.5.0"

#### Variables for Elasticsearch Exporter ####
es_exporter: "1.0.2"
es_url: "localhost"
es_port: "9200"

#### Variables for MongoDB Exporter ####
mongodb_exporter: "1.0.0"

#### Variables for Nginx Exporter ####
nginx_exporter: "0.2.0"
nginx_ip: "localhost"
nginx_port: "80"

#### Variables for Kafka Exporter ####
kafka_exporter_version: "1.2.0"
kafka_ip: "localhost"
kafka_port: "9092"

#### Variables for MySQLD Exporter ####
mysql_exporter_version: "0.11.0"
prometheus_mysqld_exporter_env: 'exporter:password@(localhost:3306)/'
